BIOIN-1755-move-single-cell-to-ugbio-utils
Ultimagen/VariantCalling pull request #200
Opened 2024-08-18 12:10 UTC by inbalzelig-ugi

Remove single cell related files, reorder some utils and move them to ugbio_core

2024-09-02 19:47 UTC, avigailmo commented on ugvc/pipelines/single_cell_qc/test/resources/insert_subsample.fastq.gz
I didn't see this resource in the ugbio pr. Was this resource not used?

2024-09-02 19:55 UTC, avigailmo requested changes
two issues:
1) many test resources were deleted and missing from ugbio_single_cell. Is this on purpose?
2) all _utils scripts shouldn't be in ugvc - you've moved them to ugbio_core

2024-09-02 19:55 UTC, avigailmo commented on ugvc/pipelines/single_cell_qc/test/resources/single_cell_qc_stats.scRNA.applicationQC.h5
same.
I didn't see this resource in the ugbio pr. Was this resource not used?

2024-09-02 19:55 UTC, avigailmo commented on ugvc/pipelines/single_cell_qc/test/resources/single_cell_qc_stats_no_shortlist.scRNA.applicationQC.h5
same

2024-09-02 19:55 UTC, avigailmo commented on ugvc/utils/plotting_utils.py
this file was moved to ugbio_core, why we need it also here?

2024-09-02 19:55 UTC, avigailmo commented on ugvc/utils/report_utils.py
same. we should use ugbio_core.report_utils

2024-09-02 19:55 UTC, avigailmo commented on ugvc/utils/sorter_utils.py
same

2024-09-02 19:55 UTC, avigailmo commented on ugvc/utils/trimmer_utils.py
same

2024-09-04 06:16 UTC, inbalzelig-ugi commented on ugvc/pipelines/single_cell_qc/test/resources/insert_subsample.fastq.gz
It is in ugbio-utils, under src/single_cell/tests/resources/insert_subsample.fastq.gz

2024-09-04 06:54 UTC, avigailmo approved these changes

2024-09-05 08:30 UTC, merged