Cnv calling using cnmops
Ultimagen/VariantCalling pull request #217
Opened 2022-07-18 12:36 UTC by TammushB

This PR contains R scripts related to CNV calling. 
Additionally, added a corresponding conda environment and updated the build_vc_docker script accordingly.

2022-07-18 12:46 UTC, ilyasoifer approved these changes

2022-07-18 12:46 UTC, ilyasoifer commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +suppressPackageStartupMessages(library(cn.mops))
License

2022-07-18 12:50 UTC, ilyasoifer commented
I think our code has to carry the license (like all pipeline scripts in ugvc do)
________________________________
From: TammushB ***@***.***>
Sent: 18 July 2022 3:49 PM
To: Ultimagen/VariantCalling ***@***.***>
Cc: Ilya Soifer ***@***.***>; Review requested ***@***.***>
Subject: Re: [Ultimagen/VariantCalling] Cnv calling using cnmops (PR #217)


@TammushB commented on this pull request.

________________________________

In ugvc/cnv/cnv_calling_using_cnmops.R<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimagen%2FVariantCalling%2Fpull%2F217%23discussion_r923334828&data=05%7C01%7Cilya.soifer%40ultimagen.com%7C501129f3957241376dbc08da68bbf614%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C637937453751055715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hQwQjRzB8BXBFF5p6pfu%2FYSpiYyKErL5KrwhZlA2Yio%3D&reserved=0>:

> @@ -0,0 +1,40 @@
+suppressPackageStartupMessages(library(cn.mops))


License LGPL (>= 2.0)
documented here : https://bioconductor.org/packages/release/bioc/manuals/cn.mops/man/cn.mops.pdf<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbioconductor.org%2Fpackages%2Frelease%2Fbioc%2Fmanuals%2Fcn.mops%2Fman%2Fcn.mops.pdf&data=05%7C01%7Cilya.soifer%40ultimagen.com%7C501129f3957241376dbc08da68bbf614%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C637937453751055715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WCvRdiBa979FgBKpzoeruVvBN7TTvHYgWWXulGr2TmY%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimagen%2FVariantCalling%2Fpull%2F217%23discussion_r923334828&data=05%7C01%7Cilya.soifer%40ultimagen.com%7C501129f3957241376dbc08da68bbf614%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C637937453751211966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KYgCFpXKKkGgtLeFg5EGa7LYjYeW6nPu6Oa0VQFVlpg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGDPRCO3GZCZN22DMNTBIHLVUVHFXANCNFSM534DPMPQ&data=05%7C01%7Cilya.soifer%40ultimagen.com%7C501129f3957241376dbc08da68bbf614%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C637937453751211966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ryg9mN7NqFrbsQDNZu%2F3QzQOmKZ%2ByMPf5MKcSYfi2E0%3D&reserved=0>.
You are receiving this because your review was requested.Message ID: ***@***.***>

________________________________

CONFIDENTIALITY NOTICE: This message (including any attachments) should be presumed to contain confidential, proprietary, privileged and/or private information. Any disclosure, reproduction, distribution or other use of this message or any attachments by any individual or entity without express permission of the sender is prohibited. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments.

2022-07-19 06:02 UTC, TammushB commented
Yet, these files are not pipeline; they are utilities. 
We can create a pipeline/wrapper that will allow running locally for small files.

2022-07-19 11:22 UTC, gilhornung commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +                    help="input cohort reads count file in Rdata format")
typo: "input cohort read counts file in Rdata format"

2022-07-19 11:24 UTC, gilhornung commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +                    help="min width parameter value",
Uninformative help

2022-07-19 11:29 UTC, gilhornung commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +save(resCNMOPS_Int,file="cohort.cnmops.RData")
Use saveRDS instead of save()

2022-07-19 11:37 UTC, gilhornung commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +write.csv(df_cnvr,"cohort.cnmops.cnvr.csv", row.names = FALSE,quote=FALSE)
I see that in the output there is a character CN0, CN1, CN2 etc. Are there any more options? If not, I suggest to save integer values (0, 1, 2 ...) instead. Will be better for downstream applications.

2022-07-19 11:42 UTC, gilhornung commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +write.csv(df_cnvr,"cohort.cnmops.cnvr.csv", row.names = FALSE,quote=FALSE)
Maybe IntegerCopyNumbers does this? Unclear to me

2022-07-19 11:44 UTC, gilhornung commented on ugvc/cnv/get_reads_count_from_bam.R
> +                    help="chromosomes names in comma seperated format. e.g, chr1,chr2,chrX" ,
Typo: chromosome names

2022-07-19 11:45 UTC, gilhornung commented on ugvc/cnv/get_reads_count_from_bam.R
> +                    help="number of parallel process",
Typo: processes

2022-07-19 12:05 UTC, gilhornung commented on ugvc/cnv/merge_reads_count_sample_to_cohort.R
> +RC_obj<-load(cohort_reads_count_file)
Prefer rds over Rdata

2022-07-19 12:07 UTC, gilhornung commented on ugvc/cnv/get_reads_count_from_bam.R
> +write.csv(as.data.frame(bamDataRanges_RC),paste(args$base_file_name,".ReadCounts.csv",sep=""),row.names = FALSE)
Don't think you need to a csv file. We already have the bigwigs from the pipeline and can work with them

2022-07-19 12:08 UTC, gilhornung commented on ugvc/cnv/get_reads_count_from_bam.R
> +save(bamDataRanges_RC, file=paste(args$base_file_name,".ReadCounts.Rdata",sep = ""))
Use saveRDS() instead of save()

2022-07-19 12:11 UTC, gilhornung commented on ugvc/cnv/merge_reads_count_sample_to_cohort.R
> +save(merged_cohort_reads_count,file="merged_cohort_reads_count.RData")
saveRDS() instead of save()

2022-07-19 12:13 UTC, gilhornung commented on ugvc/cnv/merge_reads_count_sample_to_cohort.R
> +write.csv(as.data.frame(merged_cohort_reads_count),"merged_cohort_reads_count.csv", row.names = FALSE)
merged_cohort_reads_count.csv is a huge file and will probably not be used

2022-07-19 12:20 UTC, gilhornung requested changes
Major comments:
1) Remove some large csv files which will probably be never used.
2) Large csv files that will be used - save in HDF5 format instead of csv. This way or the other we will use pandas to load them. It is faster (and cheaper) to store and load in this format (small csv files can be kept in csv).

Minor comments:
1) Use RDS files instead of Rdata files. They are easier to work with, because you do not load an environment, just one object.
2) Typos

2022-07-24 11:43 UTC, TammushB commented on ugvc/cnv/get_reads_count_from_bam.R
> +write.csv(as.data.frame(bamDataRanges_RC),paste(args$base_file_name,".ReadCounts.csv",sep=""),row.names = FALSE)
changed to hdf5 files

2022-07-24 11:44 UTC, TammushB commented on ugvc/cnv/merge_reads_count_sample_to_cohort.R
> +write.csv(as.data.frame(merged_cohort_reads_count),"merged_cohort_reads_count.csv", row.names = FALSE)
changed to hdf5 file.

2022-07-24 12:00 UTC, TammushB commented on ugvc/cnv/cnv_calling_using_cnmops.R
> +write.csv(df_cnvr,"cohort.cnmops.cnvr.csv", row.names = FALSE,quote=FALSE)
saved all outputs into a single hdf5.

2022-07-25 05:35 UTC, TammushB commented
@gilhornung thanks for all informative comments. updated all outputs to RDS and hdf5 data types. 
@ilyasoifer please review filtering script with corresponding test. 
Next step will be tests for R scripts.

2022-07-27 07:21 UTC, gilhornung approved these changes
No comments

2022-07-28 15:49 UTC, ilyasoifer reviewed
Hi, 
good job, some comments, happy to discuss!

2022-07-28 15:49 UTC, ilyasoifer commented on ugvc/cnv/filter_sample_cnvs.py
> +def annotate_bed(bed_file, lcr_cutoff, lcr_file, diff_cutoff, diff_bed_file, prefix, length_cutoff=10000):
If I understand correctly, filter_by_lcr and filter_by_blocklist is pretty much the same function that is pretty generic for BED files. Can it be written as such and live in vcfbed directory?

2022-07-31 10:39 UTC, TammushB commented on ugvc/cnv/filter_sample_cnvs.py
> +def annotate_bed(bed_file, lcr_cutoff, lcr_file, diff_cutoff, diff_bed_file, prefix, length_cutoff=10000):
Done

2022-07-31 11:33 UTC, TammushB commented on ugvc/cnv/filter_sample_cnvs.py
> +    print("output files:")
Done.

2022-07-31 12:21 UTC, TammushB commented
Resolved all comments. merging this.

2022-07-31 12:22 UTC, merged