Fixed bug with python path in cloud_sync
Ultimagen/VariantCalling pull request #219
Opened 2022-07-21 08:08 UTC by kenissur

2022-07-21 09:58 UTC, ilyasoifer requested changes
Do you want to add it to scripts section in setup.py? 
This will remove the need for line 6 since cloud_sync.py will be on the path

2022-07-21 09:58 UTC, ilyasoifer commented on ugvc/scripts/cloud_sync.py
> +sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
This is not needed since we moved to pip install pattern

2022-07-21 11:21 UTC, kenissur commented on ugvc/scripts/cloud_sync.py
> +sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
Makes sense, I couldn't figure out how to do that so I'll ask Doron for help. Thanks

2022-08-18 13:11 UTC, kenissur commented on ugvc/scripts/cloud_sync.py
> +sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
Finally done, but in another branch, I'll merge from there.

2022-08-18 13:11 UTC, closed without merging