Reb methyldackel qc mstr
Ultimagen/VariantCalling pull request #239
Opened 2022-11-03 10:40 UTC by REBUltima

Hi All,
WDL for QC of methylation seq.

Output includes:
1. Concatenated jsons
2. Concatenated CSVs
3. HTML report output (version #2) following comments
4. Has 2 pytest tests for report and for methylation python code

Currently testing wdl that wraps this with `single_sample_align_markdup`.

Thanks

2022-11-03 13:21 UTC, kenissur commented
Hi Rachel. Note that your automatic pytest failed. It might be an out of memory error judging from the "Killed" message. Can you characterize how much ram it requires? If it's over the top might be best to reduce the test data size, if not maybe the GitHub workflow needs to be set to have more RAM.

2022-11-03 14:48 UTC, kenissur requested changes

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_Mbias.py
> +        json.dump(out_json, open(out_file_name, "w"), indent=2, default=str)
I am not sure that's a good way to do this. I would do:
`with open(out_file_name, "w") as file_handler:
    json.dump(out_json, file_handler, indent=2, default=str)`

The "with" clause makes sure the file is closed when finished, when you do `file_handler = open(out_file_name, "w")` You are supposed to do `file_handler.close()` afterwards.

Maybe this way is valid, I've just never seen it before.

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_Mbias.py
> +    ap_var.add_argument("--output", help="Output file prefix", type=str, required=False,
Maybe "basename" is more intuitive than "prefix", at least to me.

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_mergeContext.py
> +    ap_var = argparse.ArgumentParser(prog="process_mergeContext.py", description="Process MethylDackel mergeContext")
Same comments as before about a slightly more detailed description, same goes for the next files.

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_mergeContext.py
> +                }
I think a dictionary with the keys "keys" and "values" is super confusing. Is that what you were trying to do?

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_mergeContext.py
> +        # list_genomes: runs on [hg] or ['hg', 'Lambda', 'pUC19']
Are ['hg', 'Lambda', 'pUC19'] the only allowed values? If so I would raise an error if any genome is not in this list.

2022-11-03 14:48 UTC, kenissur commented on ugvc/methylation/process_mergeContextNoCpG.py
> +            n_cap = 200
Generally recommended to have those as optional arguments, or at least declare all the hard coded constants in the top of the file after the imports. This makes it much easier to modify in the future when needed.

2022-11-03 14:48 UTC, kenissur commented on ugvc/reports/methyldackel_qc_report.ipynb
> +    "    dict_output = {}\n",
redundnat

2022-11-03 14:48 UTC, kenissur commented on ugvc/reports/methyldackel_qc_report.ipynb
> +    "    dict_output = {x: y for x, y in list_output.groupby('table')}\n",
I think `list_output.groupby('table').groups` is already the dictionary you are creating

2022-11-06 09:54 UTC, REBUltima commented on .csv
> +/data/VariantCalling/test/resources/unit/methylation/test_methyldackel_qc_parsing/output_perRead.csv
removed

2022-11-06 10:46 UTC, REBUltima commented on build_vc_docker_meth.sh
> +#!/bin/bash
amended

2022-11-06 10:46 UTC, REBUltima commented on Dockerfile.jbvc_methyl
> +
amended, MethylDackel added to Dockerfile

2022-11-06 10:59 UTC, REBUltima commented on build_vc_docker_zbroad.sh
> +DOCKER_BASE_NAME="gcr.io/terra-project-249020/ugvc"
amended

2022-11-06 13:25 UTC, REBUltima commented on test/unit/methylation/test_methyldackel_qc_parsing.py
> +        output_prefix = f"{tmpdir}/output_Mbias"
Thanks.
I saw it in a few other test py files, so I copied what works.

2022-11-06 14:11 UTC, REBUltima commented on test/unit/methylation/test_methyldackel_qc_parsing.py
> +                f"{self.inputs_dir}/input_Mbias.bedGraph",
as above

2022-11-06 15:28 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +            n_cap = 200
done

2022-11-06 15:28 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +                    value, metric = np.histogram(x, bins=bins_pcnt)  # where bins are 0-9, 10-19.., 90-100
ok

2022-11-06 15:30 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +                    df_abs_cov = df_rel_cov = pd.DataFrame()
fixed

2022-11-06 15:47 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +                    df_pcnt = df_pcnt[df_pcnt['metric'] < n_pcnt]  # remove Nan
fixed

2022-11-06 15:50 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +                    df_pcnt['metric'] = col + "_" + df_pcnt['metric'].astype(str)
fixed

2022-11-06 16:13 UTC, noam-ultima commented
pyc files shouldn't be part of the repo - please add them to `.gitignore`

2022-11-06 16:37 UTC, noam-ultima reviewed
@REBUltima notice that some of my comments you should consider as general comments and apply to all py files: separate for different functions, try avoid inner functions (especially after if), etc.

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/ConcatCsvs.py
> +
@REBUltima  please check that the `pre-commit` python module is installed , talk to me for any problem

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/ConcatCsvs.py
> +    run(sys.argv[1:])
add newline at end of file

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/ConcatCsvs.py
> +    ap_var.add_argument("--input", help="Text file with list of CSV files", type=str, required=True)
maybe add a description of which input csv files this script handles?

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/ConcatCsvs.py
> +        del temp
is this deletion really needed?

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/ConcatCsvs.py
> +        logger.error(*exc_info)
instead you better use `logger.exception` which will print entire exception stack trace

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_Mbias.py
> +                desc = pd.DataFrame({'metric': desc.index, 'value': desc})
here the `desc` param is changed 4 times, maybe use different params for readability?
does the type of desc is same for all changes?

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_Mbias.py
> +            # Step #1: -------------- get top tables of metrics --------------
can the different steps separated for different functions? this will enhance readability

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_Mbias.py
> +            temp_dict = dict()
temp_dict is defined in next line, not needed here

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +#!/env/python
better rename of file name to `process_merge_context.py`

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +from __future__ import annotations
why is it necessary?

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +            if (key_word == 'hg'):
better: `is key_word is "hg"`

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +            idx = data_frame.chr.str.contains(pat)
add new line here

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +            idx = data_frame.chr.str.contains(pat)
@REBUltima  you may look at https://ultimagen.atlassian.net/wiki/spaces/AG/pages/1979121665/Python+Coding+Style+Guidelines and try to follow some of it

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +                    else:
maybe the `if` and the `else` can be different functions

2022-11-06 16:37 UTC, noam-ultima commented on ugvc/methylation/process_mergeContext.py
> +            def get_ctrl_genomes_data(key_word, data_frame):
not a good practice to define a sub-function after a if condition

2022-11-07 05:58 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +                    df_pcnt = df_pcnt[df_pcnt['metric'] < n_pcnt]  # remove Nan
done

2022-11-07 07:55 UTC, gilhornung commented on ugvc/methylation/ConcatCsvs.py
> +# Copyright 2022 Ultima Genomics Inc.
Yep. First thing that came into my mind when I saw this file

2022-11-07 08:00 UTC, gilhornung commented on ugvc/methylation/ConcatCsvs.py
> +    try:
I think that an `assert` at the beginning of the script is clearer than a `try` block, no?

2022-11-07 08:10 UTC, gilhornung commented on test/resources/unit/methylation/test_methyldackel_qc_parsing/ConcatCsvs.csv
> +metric,value,detail
The header column `metric,value,detail` appears in multiple places in the file. I don't think this is how it should work

2022-11-07 08:52 UTC, gilhornung commented on test/unit/methylation/test_methyldackel_qc_parsing.py
> +        assert np.all(result_csv.shape[0] ==total )
I think you can compare the entire dataframe, and not just the lengths, It should be exactly the same

2022-11-07 10:31 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +    ap_var.add_argument("--output", help="Output file prefix", type=str, required=False,
fixed

2022-11-07 10:46 UTC, REBUltima commented on ugvc/methylation/ConcatCsvs.py
> +# Copyright 2022 Ultima Genomics Inc.
fixed

2022-11-07 10:46 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +    ap_var = argparse.ArgumentParser(prog="process_mergeContext.py", description="Process MethylDackel mergeContext")
fixed

2022-11-07 10:58 UTC, REBUltima commented on test/resources/unit/methylation/test_methyldackel_qc_parsing/ConcatCsvs.csv
> +metric,value,detail
fixed

2022-11-07 11:01 UTC, gilhornung commented on ugvc/methylation/process_Mbias.py
> +            if (len(df_input.Strand.unique()) == 4):
Why do you need to separate into case of 4 strands and 2 strands? You can run a function that operates for each group in the grouped dataframe. Also - at the end all you do here is just remove the index, Why can't it be done on the entire df at once?

2022-11-07 11:08 UTC, gilhornung commented on ugvc/methylation/process_Mbias.py
> +            temp_dict = pd.DataFrame()
Why initialize a variable named 'dict' to be a DataFrame?

2022-11-07 11:40 UTC, gilhornung commented on ugvc/methylation/process_mergeContext.py
> +                                                                                 "mergeContext output summerize"
Typo: summerize -> summarize

2022-11-07 11:42 UTC, gilhornung commented on ugvc/methylation/process_mergeContext.py
> +            match = re.findall(r"chr|Lambda|pUC19", string, re.IGNORECASE)
I think it is a bad idea to hard code the names of the chromosomes

2022-11-07 11:46 UTC, gilhornung commented on ugvc/methylation/process_mergeContext.py
> +                df_genome = pd.DataFrame()
Don't think you need to initialize if the next line places a value

2022-11-07 11:50 UTC, gilhornung commented on ugvc/methylation/process_mergeContext.py
> +        with open(out_file_name, "w", encoding="utf-8") as file:
pandas.to_csv does not require you to open a file. You don't need the `with` clause

2022-11-07 12:07 UTC, gilhornung commented on ugvc/methylation/process_mergeContextNoCpG.py
> +#!/env/python
Why do you need a different script to parse The CpG and No-CpG? Don't they have the same format?

2022-11-07 12:11 UTC, gilhornung commented on ugvc/methylation/process_perRead.py
> +                                                                            " of percent methylatio, coverage"
methylatio -> methylation

2022-11-07 12:18 UTC, gilhornung commented on ugvc/methylation/process_perRead.py
> +        def calc_distrib_methylation(data_frame):
Don't you have a function that does essentially the same in process_mergeContext?
I suggest to avoid code duplication.

2022-11-07 12:19 UTC, gilhornung commented on ugvc/methylation/process_perRead.py
> +            # for pat in patterns:
What is `for pat in patterns`?

2022-11-07 12:21 UTC, gilhornung commented on ugvc/methylation/process_perRead.py
> +            # Step #2: -------------- get 2D array of metrics --------------
I think you also did exactly the same in process_mergeContext, just with different patterns

2022-11-08 07:45 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +                df_genome = pd.DataFrame()
fixed

2022-11-08 09:53 UTC, REBUltima commented on ugvc/methylation/ConcatCsvs.py
> +        logger.error(*exc_info)
Fixed. I copied it from other people's code, so it will be in other places too.

2022-11-08 09:53 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +from __future__ import annotations
list

2022-11-08 09:55 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +            if (key_word == 'hg'):
corrected to `if (key_word is "hg")`

2022-11-08 09:59 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +#!/env/python
It's a function of the MethylDackel functions, each python script is named after the function that is performed.

2022-11-08 09:59 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +            def get_ctrl_genomes_data(key_word, data_frame):
fixed

2022-11-08 10:00 UTC, REBUltima commented on ugvc/methylation/ConcatCsvs.py
> +    try:
I copied from others code

2022-11-08 10:00 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +            temp_dict = pd.DataFrame()
fixed

2022-11-08 10:01 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +            match = re.findall(r"chr|Lambda|pUC19", string, re.IGNORECASE)
discussed

2022-11-08 10:01 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +        with open(out_file_name, "w", encoding="utf-8") as file:
ok

2022-11-08 10:01 UTC, REBUltima commented on ugvc/methylation/process_perRead.py
> +                                                                            " of percent methylatio, coverage"
fixed

2022-11-08 10:02 UTC, REBUltima commented on ugvc/methylation/process_perRead.py
> +            # Step #2: -------------- get 2D array of metrics --------------
fixed

2022-11-08 10:03 UTC, REBUltima commented on ugvc/methylation/ConcatCsvs.py
> +    run(sys.argv[1:])
fixed

2022-11-08 10:12 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +            if (key_word == 'hg'):
I corrected it, then pre-commit gave an error.
https://stackoverflow.com/questions/47778889/pylint-complains-about-comparing-a-string-to-a-literal-with-is

2022-11-08 14:02 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +                    else:
A big effort, but done. Divided into 3 functions.

2022-11-08 14:03 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +            # Step #1: -------------- get top tables of metrics --------------
Done

2022-11-09 13:04 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +                desc = pd.DataFrame({'metric': desc.index, 'value': desc})
It is the same dataframe, just reformatted a little

2022-11-09 13:05 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +                df_distrib = (pd.concat([df_distrib, desc], axis=0, ignore_index=True))
I have changed this function

2022-11-09 13:06 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +        json.dump(out_json, open(out_file_name, "w"), indent=2, default=str)
resolved

2022-11-09 13:07 UTC, REBUltima commented on ugvc/methylation/ConcatCsvs.py
> +
Good advice

2022-11-09 13:20 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +            if (len(df_input.Strand.unique()) == 4):
Right.
Great advice. Changed it to more simple Python code.

2022-11-09 13:21 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +        # list_genomes: runs on [hg] or ['hg', 'Lambda', 'pUC19']
It can be [hg] or ['hg', 'Lambda', 'pUC19']
It runs on either options.

2022-11-09 13:23 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +                }
I was asked to do it so for Papyrus

2022-11-09 16:25 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +                                     description="Process MethylDackel Mbias output")
added more detailed description

2022-11-10 08:09 UTC, REBUltima commented on ugvc/reports/methyldackel_qc_report.ipynb
> +    "    dict_output = {x: y for x, y in list_output.groupby('table')}\n",
Yes. But will require changing all the downstream code that is dependent on it. 
And it's cleaner, no?

2022-11-10 08:09 UTC, REBUltima commented on ugvc/reports/methyldackel_qc_report.ipynb
> +    "    dict_output = {}\n",
removed

2022-11-10 09:00 UTC, kenissur requested changes
The code looks much neater and readable now that the functions are concentrated in one place. There is one major issue you need to fix before merging - you commited the .idea folder, which is pycharm files that should not be, so please remove them.

Other than that there is something potentially problematic about the docker creation, I am actually a little surprised it worked, but I asked for a minor change there. Once you fix both those things I suggest you create updated dockers and run the relevant wdl to completion, if it works we can merge this.

2022-11-10 09:34 UTC, gilhornung commented on ugvc/reports/single_sample_qc_create_html_report.ipynb
>    {
I am putting all comments here:
1) Why do you need the cell with `from IPython.core.interactiveshell import InteractiveShell` ?
2) In most of your functions you have a loop over the "table" column `for tbl in list_tables`. It would be better to use groupby functionality in Pandas instead of the loop. But you don't have to fix it now, it is not worth your time.
3) The plot for Lambda methylation shows too many fully methylated sites. Could this be a bug?
4) In the Lambda and pUC19 figures there are no axis labels at all
5) In the figure about the coverage the y-scale is fraction of methylation and the x label should probably be the coverage, and not Position

2022-11-10 15:24 UTC, REBUltima commented on ugvc/reports/single_sample_qc_create_html_report.ipynb
>    {
The example was not good. I updated, will send you the latest output of html.

2022-11-10 15:24 UTC, REBUltima commented on Dockerfile.jbvc
> +    conda init --all
FIxed

2022-11-11 11:35 UTC, kenissur approved these changes
Hi, looks good. There is one thing you have to fix before merging - you commit a ugvc/__pycache__ that shouldn't be there, please remove it before you squash and merge. I am approving.

2022-11-11 14:17 UTC, ilyasoifer requested changes
Hi, thanks for the contribution! 
Technically this is good, though this test fails
FAILED test/unit/methylation/test_methyldackel_qc_parsing.py::TestParsers::test_concat_methyldackel_csvs - TypeError: not all arguments converted during string formatting 

I think next step will be to add tests to methyldackel_utils.py. It will also be nice to compress the process_ ?? files into a single file and place this into `pipelines` or `scripts`. tests for those are also missing.

2022-11-11 14:17 UTC, ilyasoifer commented on ugvc/methylation/process_mergeContext.py
> +# Copyright (c) 2019 Devon Ryan and contributors
Who is that?

2022-11-11 14:17 UTC, ilyasoifer commented on ugvc/methylation/methyldackel_utils.py
> +from __future__ import annotations
Missing documentation strings in numpy format + (if possible) type annotations

2022-11-13 13:52 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +# Copyright (c) 2019 Devon Ryan and contributors
It's what we need to add, since we are using MethylDackel 
https://github.com/dpryan79/MethylDackel/blob/master/LICENSE

2022-11-13 13:52 UTC, REBUltima commented on ugvc/methylation/process_mergeContext.py
> +# Copyright (c) 2019 Devon Ryan and contributors
https://github.com/dpryan79/MethylDackel/blob/master/LICENSE

2022-11-13 13:56 UTC, gilhornung commented on ugvc/methylation/process_mergeContextNoCpG.py
> +#!/env/python
I don't understand. If you combined the two scripts, then why is this file still here?

2022-11-13 14:55 UTC, REBUltima commented on ugvc/methylation/process_mergeContextNoCpG.py
> +#!/env/python
The input is of the same format, but a) it has 2 files as input; and b) it has slightly different output.

So theoretically I can collect the 3 inputs and run slightly different functions on the `mergecontext` and `mergecontext_noCpG` inputs, and then combine them all. 

Is this necessary to do or just a recommendation for now?

2022-11-13 14:57 UTC, REBUltima commented on ugvc/methylation/methyldackel_utils.py
> +from __future__ import annotations
Im not sure what you mean - this was added by `pylint` 
What am I to do here?

2022-11-14 07:45 UTC, gilhornung approved these changes

2022-11-14 09:14 UTC, kenissur commented on ugvc/methylation/process_Mbias.py
> +    ap_var.add_argument("--output", help="Output file basename", type=str, required=False, default="process_Mbias")
Why is "output" not required? I'm pretty sure this would fail without specifying it.

2022-11-14 09:19 UTC, kenissur commented on ugvc/methylation/methyldackel_utils.py
> +from __future__ import annotations
It's not a comment about this specific lines, it's about adding documentation ([docstring](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html)) to the functions you wrote and adding type annotations, for example:

def get_dict_from_dataframe(df_input: pd.DataFrame, detail_type: str)
"""Explaining what this function does

    Takes argument and does x and y:

    Parameters
    ----------
    df_input: pd.DataFrame
        ???
    detail_type: str
        ???

    Returns
    -------

    """

2022-11-14 09:43 UTC, REBUltima commented on ugvc/methylation/methyldackel_utils.py
> +from __future__ import annotations
Thanks, now I understand. I will add.

2022-11-14 13:06 UTC, REBUltima commented on ugvc/methylation/process_Mbias.py
> +    ap_var.add_argument("--output", help="Output file basename", type=str, required=False, default="process_Mbias")
I have changed it to required in all python process_xxx files.

2022-11-15 09:10 UTC, REBUltima commented on ugvc/methylation/methyldackel_utils.py
> +from __future__ import annotations
Added

2022-11-17 08:23 UTC, ilyasoifer approved these changes

2022-11-17 08:24 UTC, REBUltima commented
VC added code to parsing and QC methylation-seq alignment

2022-11-17 08:24 UTC, merged

2022-11-17 10:32 UTC, kenissur commented
Congratulations!

From: Rachel ***@***.***>
Sent: Thursday, November 17, 2022 10:25 AM
To: Ultimagen/VariantCalling ***@***.***>
Cc: Itai Rusinek ***@***.***>; Comment ***@***.***>
Subject: Re: [Ultimagen/VariantCalling] Reb methyldackel qc mstr (PR #239)


Merged #239<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimagen%2FVariantCalling%2Fpull%2F239&data=05%7C01%7Citai.rusinek%40ultimagen.com%7Cf5986fb23cb54d772f9408dac87538e5%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C638042703044587403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QFXYKSfsho75WBrx5T41%2Fjf1sja2qxfIp43gWlW8XVA%3D&reserved=0> into master.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimagen%2FVariantCalling%2Fpull%2F239%23event-7831381277&data=05%7C01%7Citai.rusinek%40ultimagen.com%7Cf5986fb23cb54d772f9408dac87538e5%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C638042703044587403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sSFvNIFcOkbCYhbovg9C8FBzFR7czdo5s9UyjcwUP8U%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAD2BKFAWKK4LDFJ3XXWXHXDWIXTV3ANCNFSM6AAAAAARV7VEFM&data=05%7C01%7Citai.rusinek%40ultimagen.com%7Cf5986fb23cb54d772f9408dac87538e5%7Ce279335822c64d05ba11534ec733b8dd%7C0%7C0%7C638042703044744659%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EMeK%2FOhOxIAvfCN5hgKckE4bhSopLfQmqjZIbeNYN%2Fg%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>

________________________________

CONFIDENTIALITY NOTICE: This message (including any attachments) should be presumed to contain confidential, proprietary, privileged and/or private information. Information contained in this message is intended only for the recipient(s) named above. Any disclosure, reproduction, distribution or other use of this message or any attachments by any unauthorized individual or entity is strictly prohibited. If you have received this message in error, please notify the sender immediately, and delete the message and any attachments. Learn more about Ultima Genomics' Privacy Policy<https://www.ultimagenomics.com/privacy-policy>.